"""
Archivo: 02_balancea_elefantes.py
Autor: **
Propósito: Entender el uso de range()
Tarea: 
Crea un script que te imprima la canción de los elefantes:
Debe imprimir la siguiente salida, 10 veces, con la siguiente secuencia:
  - 1 elefante se balanceaba sobre la tela de una araña ……
  - 2 elefante se balanceaba sobre la tela de una araña ……
  - ...
Bonus:
Manejar cuando debe ir en singular y plural.
  - 1 elefante se balanceaba sobre la tela de una araña ……
  - 2 elefantes se balanceaban sobre la tela de una araña ……
  - ...

"""

# Escriba la solución debajo de esta línea #